services:
  postgres:
    image: postgres:16
    container_name: tamy-project-postgres
    ports:
      - '4500:5432'
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tamy-ai
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: tamy-project-redis
    ports:
      - '6379:6379'
    volumes:
      - ./docker/redis/data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.22.4
    container_name: tamy-project-weaviate
    ports:
      - '8080:8080'
    environment:
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'text2vec-openai'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
    volumes:
      - ./docker/weaviate/data:/var/lib/weaviate

  weaviate-ui:
    image: semitechnologies/weaviate-playground:latest
    container_name: tamy-project-weaviate-ui
    ports:
      - '3100:80'
    environment:
      WEAVIATE_HOST: http://weaviate:8080
      PLAYGROUND_ORIGIN: http://localhost:3100
      PERSISTENCE_PATH: /var/lib/weaviate-playground
    depends_on:
      - weaviate
