name: PR Checks

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  pnpm_setup:
    uses: ./.github/workflows/reusable-pnpm-setup.yml

  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: pnpm_setup
    steps:
      - uses: ./.github/workflows/reusable-pnpm-setup.yml@main
      - name: Install dependencies
        run: pnpm install
      - name: Run linting
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: pnpm_setup
    steps:
      - uses: ./.github/workflows/reusable-pnpm-setup.yml@main
      - name: Install dependencies
        run: pnpm install
      - name: Run tests
        run: pnpm test

  build:
    name: Build Check
    runs-on: ubuntu-latest
    needs: pnpm_setup
    steps:
      - uses: ./.github/workflows/reusable-pnpm-setup.yml@main
      - name: Install dependencies
        run: pnpm install
      - name: Build packages
        run: pnpm build
